### ISSUE TITLE
Syntax change needed for Alpine based hosts

### ISSUE THREAD

**Issue by carsten-re** [GAS85/Gotify-old_Notifications_cleanup#1]
Hi,

line 113 of gotify-delete-old-notifications.sh needs to be changed in order to calculate the date.
This is required, because the "date" implementation in busybox is different.

Origin:
Line 113:
`DateToDeleteNotifications="$(date --date="$keepDays day ago" '+%Y-%m-%d')"`

Changed:
`DateToDeleteNotifications="$(date -d "@$(( $(date +%s) - $keepDays * 24 * 60 * 60 ))" -I)"`

**Comment by GAS85** [comment]
It is not only syntax of date, there are different `awk` and `cron` at least. I need to investigate it. Make it sense to move to alpine base image at all?

**Comment by GAS85** [comment]
Please test new image in a Pull Request.
And for Alpine it is 15 MB vs 83 MB for Ubuntu.

**Comment by carsten-re** [comment]
Oh, I'm just running the script on the host, not in a container.
What I've installed in addition was (with apk add):
`jq gawk sed bash`

**Comment by GAS85** [comment]
This is exactly what I add, [check it out](https://github.com/GAS85/Gotify-old_Notifications_cleanup/blob/c758bd0c74957e3c3928c455942d66e0e64d398d/Dockerfile#L5).
